import Foundation

/// Built-in templates embedded as static strings.
enum Templates {
    static let readmeTemplate = """
        # {{name}}

        A Swift package generated by swiftanvil.
        """
    
    static let libraryStubTemplate = """
        import Foundation

        public struct {{name}} {
            public init() {}
        }
        """
    
    static let executableStubTemplate = """
        import Foundation

        print("Hello, {{name}}!")
        """
    
    static let testStubTemplate = """
        import Foundation
        import Testing

        @Test func example() async throws {
            // Write your test here.
        }
        """
    
    static let gitignoreTemplate = """
        .build/
        *.xcodeproj
        *.xcworkspace
        .DS_Store
        """
    
    /// Returns the template string for a given template name, or nil if unknown.
    static func template(named name: String) -> String? {
        switch name {
        case "readme": return readmeTemplate
        case "library": return libraryStubTemplate
        case "executable": return executableStubTemplate
        case "test": return testStubTemplate
        case "gitignore": return gitignoreTemplate
        default: return nil
        }
    }
}
